### ISSUE TITLE
Don't use fontawesome

### ISSUE THREAD

**Issue by jihunchoi** [theeluwin/theeluwin.github.io#1]
Please be so kind and use trophy emoji 🏆 instead of fontawesome's.
(I want to cut and paste the description)

**Comment by theeluwin** [comment]
PR it.

**Comment by jihunchoi** [comment]
NO

**Comment by theeluwin** [comment]
Resolved through https://github.com/theeluwin/theeluwin.github.io/commit/8afb13f6af10016a166e110504a8d930a71a1a7d. Closing issue.
